--학생 학과 테이블 생성

-- 학과 테이블
-- drop table department;
create table department (
	dptNo varchar(10) not null primary key,
    dptName varchar(30) not null,
    dptTel varchar(13) not null
);

-- 학생 테이블
-- drop table student;
create table student (
	stdNo varchar(10) not null primary key,
    stdName varchar(30) not null,
    stdYear int default 4 check (stdYear>=1 and stdYear<=4),
    stdAddress varchar(30),
    stdBirth date,
    dptNo varchar(10) not null,
    foreign key (dptNo) references department(dptNo)
);

INSERT ALL INTO department (dptNo, dptName, dptTel)
 VALUES('001', '경영학과', '02-111-1111')
 INTO department (dptNo, dptName, dptTel)
 VALUES ('002', '기계공학과', '02-222-2222')
 INTO department (dptNo, dptName, dptTel)
 VALUES ('003', '컴퓨터공학과', '02-333-3333')
 SELECT *
 FROM DUAL;


CREATE TABLE department1  (
    dptNo  VARCHAR2(10) NOT NULL PRIMARY KEY,
    dptName  VARCHAR2(30) NOT NULL,
    dptTel  VARCHAR2(13) NOT NULL
);

CREATE TABLE student1 (
    stdNo  VARCHAR2(10) NOT NULL PRIMARY KEY,
    stdName  VARCHAR2(30) NOT NULL,
    stdYear INT DEFAULT 4 CHECK (stdYear >= 1 AND stdYear <= 4),
    stdAddress  VARCHAR2(30),
    stdBirth  DATE,
    dptNo  VARCHAR2(10) NOT NULL,
    FOREIGN KEY (dptNo) REFERENCES department1 (dptNo)
);

INSERT INTO department1 VALUES ('1', '컴퓨터공학과', '02-111-1111');
INSERT INTO department1 VALUES ('2', '전자공학과', '02-222-2222');
INSERT INTO department1 VALUES ('3', '기계공학과', '02-333-3333');

INSERT INTO student1 (stdNo, stdName, stdYear, stdBirth, dptNo) VALUES ('2016001', '홍길동', 4, TO_DATE('1997-01-01', 'YYYY-MM-DD'), '1');
INSERT INTO student1 (stdNo, stdName, stdYear, stdBirth, dptNo) VALUES ('2015002', '성춘향', 3, TO_DATE('1996-12-10', 'YYYY-MM-DD'), '3');
INSERT INTO student1 (stdNo, stdName, stdYear, stdBirth, dptNo) VALUES ('2014004', '이몽룡', 2, TO_DATE('1996-03-03', 'YYYY-MM-DD'), '2');
INSERT INTO student1 (stdNo, stdName, stdYear, stdBirth, dptNo) VALUES ('2016002', '변학도', 4, TO_DATE('1995-05-07', 'YYYY-MM-DD'), '1');
INSERT INTO student1 (stdNo, stdName, stdYear, stdBirth, dptNo) VALUES ('2015003', '손흥민', 3, TO_DATE('1997-11-11', 'YYYY-MM-DD'), '2');

INSERT INTO student1 VALUES ('2016001', '홍길동', 4, NULL, TO_DATE('1997-01-01', 'YYYY-MM-DD'), '1');
INSERT INTO student1 VALUES ('2015002', '성춘향', 3, NULL, TO_DATE('1996-12-10', 'YYYY-MM-DD'), '3');
INSERT INTO student1 VALUES ('2014004', '이몽룡', 2, NULL, TO_DATE('1996-03-03', 'YYYY-MM-DD'), '2');
INSERT INTO student1 VALUES ('2016002', '변학도', 4, NULL, TO_DATE('1995-05-07', 'YYYY-MM-DD'), '1');
INSERT INTO student1 VALUES ('2015003', '손흥민', 3, NULL, TO_DATE('1997-11-11', 'YYYY-MM-DD'), '2');

INSERT INTO student1 (stdNo, stdName, stdYear, stdBirth, dptNo)
SELECT '2016001', '홍길동', 4, TO_DATE('1997-01-01', 'YYYY-MM-DD'), '1' FROM DUAL UNION ALL
SELECT '2015002', '성춘향', 3, TO_DATE('1996-12-10', 'YYYY-MM-DD'), '3' FROM DUAL UNION ALL
SELECT '2014004', '이몽룡', 2, TO_DATE('1996-03-03', 'YYYY-MM-DD'), '2' FROM DUAL UNION ALL
SELECT '2016002', '변학도', 4, TO_DATE('1995-05-07', 'YYYY-MM-DD'), '1' FROM DUAL UNION ALL
SELECT '2015003', '손흥민', 3, TO_DATE('1997-11-11', 'YYYY-MM-DD'), '2' FROM DUAL;

SELECT * FROM student1;

--0806 연습 문제
CREATE TABLE book(
    bookNum VARCHAR2(10),
    bookName VARCHAR2(10),
    BookPrice VARCHAR2(10),
    BookStart VARCHAR2(10),
    BookWhere VARCHAR2(10)
    );
    SELECT * FROM book;
   UPDATE book SET bookPrice = 22000 WHERE bookName = '데이터베이스';s
   SELECT * FROM book;
   
 SELECT CLIENTNAME, CLIENTBIRTH, CLIENTGENDER
FROM CLIENT;

SELECT DISTINCT CLIENTADDRESS
FROM CLIENT;

SELECT CLIENTNAME, CLIENTHOBBY
FROM CLIENT
WHERE CLIENTHOBBY IN ('축구', '등산');

SELECT DISTINCT BOOKAUTHOR
FROM BOOK
WHERE BOOKAUTHOR LIKE '_길%';

SELECT BOOKNAME, BOOKAUTHOR, BOOKDATE
FROM BOOK
WHERE TO_CHAR(BOOKDATE, 'YYYY') = '2018';

SELECT *
FROM BOOKSALE
WHERE CLIENTNO NOT IN (1, 2);

SELECT CLIENTNAME, CLIENTADDRESS, CLIENTHOBBY
FROM CLIENT
WHERE CLIENTHOBBY IS NOT NULL
  AND CLIENTADDRESS LIKE '서울%';

SELECT BOOKNAME, BOOKAUTHOR, BOOKPRICE, BOOKSTOCK
FROM BOOK
WHERE BOOKPRICE >= 25000
  AND BOOKAUTHOR LIKE '%길동%';

SELECT *
FROM BOOK
WHERE BOOKPRICE BETWEEN 20000 AND 25000;

SELECT BOOKNAME, BOOKAUTHOR
FROM BOOK
WHERE BOOKAUTHOR NOT LIKE '%길동%';

SELECT BOOKNAME, BOOKAUTHOR, BOOKPRICE
FROM BOOK
ORDER BY BOOKPRICE DESC, BOOKAUTHOR ASC;

SELECT SUM(BOOKSTOCK) AS TOTAL_STOCK
FROM BOOK
WHERE BOOKAUTHOR LIKE '%길동%';

SELECT MAX(BOOKPRICE) AS MAX_PRICE,
       MIN(BOOKPRICE) AS MIN_PRICE
FROM BOOK
WHERE PUBNO = 1;

SELECT PUBNO,
       SUM(BOOKSTOCK) AS TOTAL_STOCK,
       AVG(BOOKSTOCK) AS AVG_STOCK
FROM BOOK
GROUP BY PUBNO
ORDER BY TOTAL_STOCK DESC;

SELECT CLIENTNO,
       SUM(BSQTY) AS TOTAL_QTY,
       COUNT(*) AS ORDER_COUNT
FROM BOOKSALE
GROUP BY CLIENTNO
HAVING COUNT(*) >= 2;

SELECT B.BOOKNO,
       B.BOOKNAME,
       P.PUBNAME
FROM BOOK B
JOIN PUBLISHER P
ON B.PUBNO = P.PUBNO;

SELECT B.BOOKNAME,
       B.BOOKAUTHOR,
       P.PUBNAME
FROM BOOK B
JOIN PUBLISHER P
ON B.PUBNO = P.PUBNO
WHERE P.PUBNAME = '서울 출판사';

SELECT DISTINCT B.BOOKNAME
FROM BOOK B
JOIN PUBLISHER P
ON B.PUBNO = P.PUBNO
JOIN BOOKSALE BS
ON B.BOOKNO = BS.BOOKNO
WHERE P.PUBNAME = '정보출판사';

SELECT C.CLIENTNAME,
       B.BOOKNAME,
       B.BOOKPRICE,
       BS.BSQTY
FROM CLIENT C
JOIN BOOKSALE BS
ON C.CLIENTNO = BS.CLIENTNO
JOIN BOOK B
ON BS.BOOKNO = B.BOOKNO
WHERE B.BOOKPRICE >= 30000;

SELECT B.BOOKNAME,
       C.CLIENTNAME,
       C.CLIENTGENDER,
       C.CLIENTADDRESS
FROM CLIENT C
JOIN BOOKSALE BS
ON C.CLIENTNO = BS.CLIENTNO
JOIN BOOK B
ON BS.BOOKNO = B.BOOKNO
WHERE B.BOOKNAME = '안드로이드 프로그래밍'
ORDER BY C.CLIENTNAME;

SELECT SUM(B.BOOKPRICE * BS.BSQTY) AS TOTAL_SALES
FROM BOOK B
JOIN PUBLISHER P
ON B.PUBNO = P.PUBNO
JOIN BOOKSALE BS
ON B.BOOKNO = BS.BOOKNO
WHERE P.PUBNAME = '도서출판 강남';

SELECT BS.BSDATE,
       P.PUBNAME,
       B.BOOKNAME,
       B.BOOKPRICE,
       BS.BSQTY,
       B.BOOKPRICE * BS.BSQTY AS ORDER_PRICE
FROM BOOKSALE BS
JOIN BOOK B
ON BS.BOOKNO = B.BOOKNO
JOIN PUBLISHER P
ON B.PUBNO = P.PUBNO
WHERE P.PUBNAME = '서울 출판사';

SELECT B.BOOKNO,
       B.BOOKNAME,
       SUM(BS.BSQTY) AS TOTAL_QTY
FROM BOOK B
JOIN BOOKSALE BS
ON B.BOOKNO = BS.BOOKNO
GROUP BY B.BOOKNO, B.BOOKNAME;

SELECT C.CLIENTNAME,
       SUM(B.BOOKPRICE * BS.BSQTY) AS TOTAL_PRICE
FROM CLIENT C
JOIN BOOKSALE BS
ON C.CLIENTNO = BS.CLIENTNO
JOIN BOOK B
ON BS.BOOKNO = B.BOOKNO
GROUP BY C.CLIENTNAME
HAVING SUM(B.BOOKPRICE * BS.BSQTY) >= 100000;

SELECT C.CLIENTNAME,
       BS.BSDATE,
       B.BOOKNAME,
       BS.BSQTY,
       P.PUBNAME
FROM CLIENT C
JOIN BOOKSALE BS
ON C.CLIENTNO = BS.CLIENTNO
JOIN BOOK B
ON BS.BOOKNO = B.BOOKNO
JOIN PUBLISHER P
ON B.PUBNO = P.PUBNO
WHERE P.PUBNAME = '도서출판 강남'
ORDER BY C.CLIENTNAME;